@extends('layouts.app')
@section('content')
        <section class="banner-section yii-banner">
            <div class="container">
                <div class="contents">
                    <h1>Yii Framework Development</h1>
                </div>
            </div>
        </section>
        <section class="career-our-values-sec">
            <div class="container">
                <div class="row">
                    <div class="col-md-12">
                        <h3>Yii Development Services</h3>
                        <ul class="our-values">
                            <li>Use MVC architecture</li>
                            <li>Custom Yii web development</li>
                            <li>Migration to Yii</li>
                            <li>Yii extension & module development</li>
                            <li>Custom web service development</li>
                            <li>AJAX-enabled widgets integration</li>
                            <li>Enterprise Portals</li>
                            <li>Scalable Yii framework based products</li>
                        </ul>
                    </div>
                </div>
            </div>
        </section>
        <section class="related-service">
            <div class="container">
                <div class="our-perks">
                    <h3>Reasons to choose yii for web development</h3>
                    <div class="row">
                        <div class="col-md-6">
                            <ul class="icon-tik-list list1">
                                <li>
                                    <h6>Model-View-Controller (MVC)</h6>
                                    <p>The popular design pattern plays a vital role in making a website extremely organized</p>
                                </li>
                                <li>
                                    <h6>Highly Extensible</h6>
                                    <p>Virtually every component of the framework is extensible enough to suit needs of the user</p>
                                </li>
                                <li>
                                    <h6>Rapid Development</h6>
                                    <p>CRUD operations generated by Yii makes web applications running in no time </p>
                                </li>
                                <li>
                                    <h6>Advanced Caching System</h6>
                                    <p>You can save both SQL/Active and static data record queries, reducing time in page loading</p>
                                </li>
                            </ul>
                        </div>
                        <div class="col-md-6">
                            <ul class="icon-tik-list list2">
                                <li>
                                    <h6>Database Access Object</h6>
                                    <p>From accessing DBMS to reducing the need for writing SQL queries again, it makes coding easier</p>
                                </li>
                                <li>
                                    <h6>Encourages Testing</h6>
                                    <p>Integrated with Codeception, it simplifies the process of testing units & functional tests for your app</p>
                                </li>
                                <li>
                                    <h6>Security Concerns</h6>
                                    <p>Whether it is illicit access or malicious codes, the framework secures the website.</p>
                                </li>
                                <li>
                                    <h6>Utilize Modern Technologies</h6>
                                    <p>Provide you with a clear access to pre-existing files and packages for a better look and functionality.</p>
                                </li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </section>
        <section class="portfolio-outer padding-lg">
            <div class="container text-center">
                <h2 class="main-title">Related Portfilio</h2>
                <ul class="row portfolio clearfix isotopeContainer">
                    <li class="col-6 col-md-4 isotopeSelector yiitwo">
                        <div class="inner">
                            <div class="overlay">
                                <h2>Qaiwa</h2>
                                <p>Yii/Yii2</p>
                                <a class="galleryItem" href="{{asset('img/portfoliyo/04.png')}}"><span class="icon-expand"></span></a></div>
                            <figure><img src="{{asset('img/portfoliyo/04.png')}}" class="img-responsive" alt=""></figure>
                        </div>
                    </li>
                    <li class="col-6 col-md-4 isotopeSelector yiitwo">
                        <div class="inner">
                            <div class="overlay">
                                <h2>InQfy</h2>
                                <p>Yii/Yii2</p>
                                <a class="galleryItem" href="{{asset('img/portfoliyo/briskbraintech-inqfy.png')}}"><span class="icon-expand"></span></a></div>
                            <figure><img src="{{asset('img/portfoliyo/briskbraintech-inqfy.png')}}" class="img-responsive" alt=""></figure>
                        </div>
                    </li>
                    <li class="col-6 col-md-4 isotopeSelector yiitwo">
                        <div class="inner">
                            <div class="overlay">
                                <h2>Foodmirch</h2>
                                <p>Yii/Yii2</p>
                                <a class="galleryItem" href="{{asset('img/portfoliyo/briskbraintech-yii-1.png')}}"><span class="icon-expand"></span></a></div>
                            <figure><img src="{{asset('img/portfoliyo/briskbraintech-yii-1.png')}}" class="img-responsive" alt=""></figure>
                        </div>
                    </li>
                </ul>
            </div>
        </section>
       @endsection
